
import { CountryOption, ProficiencyLevelOption } from './types';

export const availableLanguages: string[] = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Dutch',
  'Russian',
  'Chinese',
  'Japanese',
  'Korean',
  'Arabic',
  'Hindi',
  'Turkish',
  'Polish',
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Greek',
  'Czech',
  'Slovak',
  'Hungarian',
  'Romanian',
  'Bulgarian',
  'Ukrainian',
  'Thai',
  'Vietnamese',
  'Indonesian',
  'Malay',
  'Filipino',
  'Hebrew',
  'Bengali',
  'Punjabi',
  'Urdu',
];

// Countries with codes, flags and calling codes
export const countries: CountryOption[] = [
  { value: 'us', label: 'United States', flag: '🇺🇸', calling_code: '+1' },
  { value: 'gb', label: 'United Kingdom', flag: '🇬🇧', calling_code: '+44' },
  { value: 'ca', label: 'Canada', flag: '🇨🇦', calling_code: '+1' },
  { value: 'au', label: 'Australia', flag: '🇦🇺', calling_code: '+61' },
  { value: 'de', label: 'Germany', flag: '🇩🇪', calling_code: '+49' },
  { value: 'fr', label: 'France', flag: '🇫🇷', calling_code: '+33' },
  { value: 'es', label: 'Spain', flag: '🇪🇸', calling_code: '+34' },
  { value: 'it', label: 'Italy', flag: '🇮🇹', calling_code: '+39' },
  { value: 'jp', label: 'Japan', flag: '🇯🇵', calling_code: '+81' },
  { value: 'cn', label: 'China', flag: '🇨🇳', calling_code: '+86' },
  { value: 'in', label: 'India', flag: '🇮🇳', calling_code: '+91' },
  { value: 'br', label: 'Brazil', flag: '🇧🇷', calling_code: '+55' },
  { value: 'mx', label: 'Mexico', flag: '🇲🇽', calling_code: '+52' },
  { value: 'ru', label: 'Russia', flag: '🇷🇺', calling_code: '+7' },
  { value: 'za', label: 'South Africa', flag: '🇿🇦', calling_code: '+27' },
  { value: 'kr', label: 'South Korea', flag: '🇰🇷', calling_code: '+82' },
  { value: 'nl', label: 'Netherlands', flag: '🇳🇱', calling_code: '+31' },
  { value: 'se', label: 'Sweden', flag: '🇸🇪', calling_code: '+46' },
  { value: 'sg', label: 'Singapore', flag: '🇸🇬', calling_code: '+65' },
  { value: 'ae', label: 'United Arab Emirates', flag: '🇦🇪', calling_code: '+971' },
  { value: 'sa', label: 'Saudi Arabia', flag: '🇸🇦', calling_code: '+966' },
  { value: 'ar', label: 'Argentina', flag: '🇦🇷', calling_code: '+54' },
  { value: 'be', label: 'Belgium', flag: '🇧🇪', calling_code: '+32' },
  { value: 'ch', label: 'Switzerland', flag: '🇨🇭', calling_code: '+41' },
  { value: 'cl', label: 'Chile', flag: '🇨🇱', calling_code: '+56' },
  { value: 'co', label: 'Colombia', flag: '🇨🇴', calling_code: '+57' },
  { value: 'dk', label: 'Denmark', flag: '🇩🇰', calling_code: '+45' },
  { value: 'eg', label: 'Egypt', flag: '🇪🇬', calling_code: '+20' },
  { value: 'fi', label: 'Finland', flag: '🇫🇮', calling_code: '+358' },
  { value: 'gr', label: 'Greece', flag: '🇬🇷', calling_code: '+30' },
  { value: 'hk', label: 'Hong Kong', flag: '🇭🇰', calling_code: '+852' },
  { value: 'hu', label: 'Hungary', flag: '🇭🇺', calling_code: '+36' },
  { value: 'id', label: 'Indonesia', flag: '🇮🇩', calling_code: '+62' },
  { value: 'ie', label: 'Ireland', flag: '🇮🇪', calling_code: '+353' },
  { value: 'il', label: 'Israel', flag: '🇮🇱', calling_code: '+972' },
  { value: 'my', label: 'Malaysia', flag: '🇲🇾', calling_code: '+60' },
  { value: 'ng', label: 'Nigeria', flag: '🇳🇬', calling_code: '+234' },
  { value: 'no', label: 'Norway', flag: '🇳🇴', calling_code: '+47' },
  { value: 'nz', label: 'New Zealand', flag: '🇳🇿', calling_code: '+64' },
  { value: 'ph', label: 'Philippines', flag: '🇵🇭', calling_code: '+63' },
  { value: 'pl', label: 'Poland', flag: '🇵🇱', calling_code: '+48' },
  { value: 'pt', label: 'Portugal', flag: '🇵🇹', calling_code: '+351' },
  { value: 'tr', label: 'Turkey', flag: '🇹🇷', calling_code: '+90' },
  { value: 'ua', label: 'Ukraine', flag: '🇺🇦', calling_code: '+380' },
  { value: 'vn', label: 'Vietnam', flag: '🇻🇳', calling_code: '+84' },
].sort((a, b) => a.label.localeCompare(b.label));

export const proficiencyLevels: ProficiencyLevelOption[] = [
  {
    value: 'native',
    label: 'Native',
    description: 'You grew up speaking this language or you speak it as well as a native speaker.'
  },
  {
    value: 'fluent',
    label: 'Fluent',
    description: 'You can express yourself fluently and spontaneously without much obvious searching for expressions.'
  },
  {
    value: 'conversational',
    label: 'Conversational',
    description: 'You can deal with most situations likely to arise while traveling in an area where the language is spoken.'
  }
];
